=== vHc05/pokemon_teams/PokemonTeams.dtd
<!ELEMENT pokemon_teams (team+)>
<!ELEMENT team (t:name,format, pokemon+)>
<!ATTLIST team xmlns:t CDATA #REQUIRED>
<!ELEMENT t:name (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT pokemon (p:name, type, teratype?,level,gender?,shiny,item,ability,hidden_ability?,stats+,moves)>
<!ATTLIST pokemon xmlns:p CDATA #REQUIRED>
<!ELEMENT p:name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT teratype (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT stats (hp,atk,def,spa,spd,spe)>
<!ELEMENT hp (#PCDATA)>
<!ELEMENT atk (#PCDATA)>
<!ELEMENT def (#PCDATA)>
<!ELEMENT spa (#PCDATA)>
<!ELEMENT spd (#PCDATA)>
<!ELEMENT spe (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT shiny (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT ability (#PCDATA)>
<!ELEMENT hidden_ability (#PCDATA)>
<!ELEMENT moves (move+)>
<!ELEMENT move (m:name,mtype,category,description)>
<!ATTLIST move xmlns:m CDATA #REQUIRED>
<!ELEMENT m:name (#PCDATA)>
<!ELEMENT mtype (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== vHc05/pokemon_teams/PokemonTeams.xml
<!DOCTYPE pokemon_teams SYSTEM "PokemonTeams.dtd">

<pokemon_teams>
    <team xmlns:t="https://trabajogrupalvictorymarcos.es/team">
        <t:name>Dondozo + Ursaluna Bloodmoon</t:name>
        <format>VGC 2023 Regulation E</format>
        <pokemon  xmlns:p="https://trabajogrupalvictorymarcos.es/pokemon">
            <p:name>Dondozo</p:name>
            <type>Water</type>
            <teratype>Flying</teratype>
            <level>50</level>
            <shiny>No</shiny>
            <item>Air Balloon</item>
            <ability>Oblivius</ability>
            <hidden_ability>Water Veil</hidden_ability>
            <stats>
                <hp>256</hp>
                <atk>136</atk>
                <def>136</def>
                <spa>76</spa>
                <spd>114</spd>
                <spe>56</spe>
            </stats>
            <moves>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Protect</m:name>
                    <mtype>Normal</mtype>
                    <category>Status</category>
                    <description>Evita que los movimientos afecten al usuario este turno.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Wave Crash</m:name>
                    <mtype>Water</mtype>
                    <category>Physical</category>
                    <description>Tiene un 33% de retroceso.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Order Up</m:name>
                    <mtype>Dragon</mtype>
                    <category>Physical</category>
                    <description>Rizado|Caído|Elástico comido: +1 Atk|Def|Spe</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Heavy Slam</m:name>
                    <mtype>Steel</mtype>
                    <category>Physical</category>
                    <description>Más potencia cuanto más pesado sea el usuario que el objetivo</description>
                </move>
            </moves>
        </pokemon>
        <pokemon  xmlns:p="https://trabajogrupalvictorymarcos.es/pokemon">
            <p:name>Ursaluna BloodMoon</p:name>
            <type>Ground-Normal</type>
            <teratype>Ground</teratype>
            <level>50</level>
            <gender>Male</gender>
            <shiny>No</shiny>
            <item>Sitrus Berry</item>
            <ability>Minds Eye</ability>
            <stats>
                <hp>219</hp>
                <atk>67</atk>
                <def>141</def>
                <spa>174</spa>
                <spd>114</spd>
                <spe>73</spe>
            </stats>
            <moves>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Protect</m:name>
                    <mtype>Normal</mtype>
                    <category>Status</category>
                    <description>Evita que los movimientos afecten al usuario este turno.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Blood Moon</m:name>
                    <mtype>Normal</mtype>
                    <category>Special</category>
                    <description>No se puede utilizar dos veces seguidas.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Hyper Voice</m:name>
                    <mtype>Normal</mtype>
                    <category>Special</category>
                    <description>Ningún efecto adicional. Golpea a los enemigos adyacentes.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Earth Power</m:name>
                    <mtype>Ground</mtype>
                    <category>Special</category>
                    <description>10% de probabilidad de reducir el Sp del objetivo. Def por 1.</description>
                </move>
            </moves>
        </pokemon>
        <pokemon  xmlns:p="https://trabajogrupalvictorymarcos.es/pokemon">
            <p:name>Cresselia</p:name>
            <type>Physic</type>
            <teratype>Physic</teratype>
            <level>50</level>
            <gender>Female</gender>
            <shiny>No</shiny>
            <item>Safety Goggles</item>
            <ability>Levitate</ability>
            <stats>
                <hp>227</hp>
                <atk>67</atk>
                <def>152</def>
                <spa>95</spa>
                <spd>166</spd>
                <spe>105</spe>
            </stats>
            <moves>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Trick Room</m:name>
                    <mtype>Physic</mtype>
                    <category>Status</category>
                    <description>Va último. Durante 5 turnos, el orden de los turnos se invierte.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Lunar Blessing</m:name>
                    <mtype>Physic</mtype>
                    <category>Status</category>
                    <description>Usuario y aliados: curado 1/4 de HP máximo, estado curado.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Ally Switch</m:name>
                    <mtype>Physic</mtype>
                    <category>Status</category>
                    <description>Usuario y aliado intercambian posiciones; usarlo nuevamente puede fallar.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Moonblast</m:name>
                    <mtype>Fairy</mtype>
                    <category>Special</category>
                    <description>30% de probabilidad de reducir el Sp del objetivo. Atk por 1.</description>
                </move>
            </moves>
        </pokemon>
        <pokemon  xmlns:p="https://trabajogrupalvictorymarcos.es/pokemon">
            <p:name>Chi-Yu</p:name>
            <type>Fire-Dark</type>
            <teratype>Ghost</teratype>
            <level>50</level>
            <shiny>No</shiny>
            <item>Life Orb</item>
            <ability>Beads of Ruin</ability>
            <stats>
                <hp>159</hp>
                <atk>76</atk>
                <def>101</def>
                <spa>172</spa>
                <spd>144</spd>
                <spe>150</spe>
            </stats>
            <moves>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Protect</m:name>
                    <mtype>Noraml</mtype>
                    <category>Status</category>
                    <description>Evita que los movimientos afecten al usuario este turno.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Heat Wave</m:name>
                    <mtype>Fire</mtype>
                    <category>Special</category>
                    <description>10% de probabilidad de quemar a los enemigos.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Dark Pulse</m:name>
                    <mtype>Dark</mtype>
                    <category>Special</category>
                    <description>20% de posibilidades de hacer que el objetivo se estremezca.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Tera Blast</m:name>
                    <mtype>Normal</mtype>
                    <category>Special</category>
                    <description>Si está terastalizado: Phys. si Atk > SpA, escriba = Tera.</description>
                </move>
            </moves>
        </pokemon>
        <pokemon  xmlns:p="https://trabajogrupalvictorymarcos.es/pokemon">
            <p:name>Iron Hands</p:name>
            <type>Electric-Fighting</type>
            <teratype>Fighting</teratype>
            <level>50</level>
            <shiny>No</shiny>
            <item>Assault Vest</item>
            <ability>Quark Drive</ability>
            <stats>
                <hp>241</hp>
                <atk>205</atk>
                <def>134</def>
                <spa>63</spa>
                <spd>108</spd>
                <spe>71</spe>
            </stats>
            <moves>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Fake Out</m:name>
                    <mtype>Normal</mtype>
                    <category>Physical</category>
                    <description>Golpea primero. Primero salga solamente. 100% de posibilidades de estremecerse.</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Heavy Slam</m:name>
                    <mtype>Steel</mtype>
                    <category>Physical</category>
                    <description>Más potencia cuanto más pesado sea el usuario que el objetivo</description>
                </move>
                <move xmlns:m="https://trabajogrupalvictorymarcos.es/move">
                    <m:name>Wild Charge</m:name>
                    <mtype>Electric</mtype>
                    <category>Physical</category>
